### ISSUE TITLE
Errror provisioning chromedriver on centos7

### ISSUE THREAD

**Issue by mcrmfc** [dhoer/chef-selenium#16]
When running on my centos7 vm (which correctly identifies as `centos` platform) I run into trouble with [this line](https://github.com/dhoer/chef-selenium/blob/master/recipes/chromedriver.rb#L34).

```
==> default: 
==> default: NoMethodError
==> default: -------------
==> default: No resource or method named `windows_zipfile' for `Chef::Recipe "chromedriver"'
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /tmp/vagrant-chef/ac4c8aa2284621160c918e90286c6b9e/cookbooks/selenium/recipes/chromedriver.rb:34:in `rescue in from_file'
==> default:   /tmp/vagrant-chef/ac4c8aa2284621160c918e90286c6b9e/cookbooks/selenium/recipes/chromedriver.rb:27:in `from_file'
==> default: 
==> default:   /tmp/vagrant-chef/ac4c8aa2284621160c918e90286c6b9e/cookbooks/mcr-selenium-grid/recipes/default.rb:14:in `from_file'
==> default: 
==> default: Relevant File Content:
==> default: ----------------------
==> default: /tmp/vagrant-chef/ac4c8aa2284621160c918e90286c6b9e/cookbooks/selenium/recipes/chromedriver.rb:
==> default: 
==> default: 
==> default:  27:  begin
==> default:  28:    batch 'unzip chromedriver' do
==> default: 
==> default:  29:      code "powershell.exe -nologo -noprofile -command \"& { Add-Type -A 'System.IO.Compression.FileSystem';"\
==> default:  30:        " [IO.Compression.ZipFile]::ExtractToDirectory('#{cache_path}', '#{driver_path}'); }\""
==> default:  31:      action :nothing
==> default:  32:    end
==> default: 
==> default:  33:  rescue # cheesy attempt at backward compatibility
==> default: 
==> default:  34>>   windows_zipfile driver_path do
==> default:  35:      source cache_path
==> default: 
==> default:  36:      action :unzip
==> default:  37:    end
==> default: 
==> default:  38:  end
==> default:  39:  
==> default: 
==> default:  40:  execute 'unzip chromedriver' do
==> default:  41:    command "unzip -o #{cache_path} -d #{driver_path} && chmod -R 0755 #{driver_path}"
==> default: 
==> default:  42:    action :nothing
==> default: 
==> default:  43:  end
```

I can work around this by wrapping this whole begin/rescue/end with a `if platform?('windows')` but not sure if that's just fixing the symptom rather than the root cause?  

It feels like this block shouldn't be evaluated if we are not on Windows?

Any assistance would be great, happy to do a PR and add any tests just want to be sure I understand the intention?

Cheers,
Matt.

**Comment by dhoer** [comment]
Thanks Matt, 
I have another issue related to this section of code for windows 7.   I will try to get a patch out in the next several days.

**Comment by dhoer** [comment]
Thanks for reporting this issue.  Please let me know if this is fixed in latest release.

**Comment by mcrmfc** [comment]
Thanks so much - working great now!
