### ISSUE TITLE
Firefox on Ubuntu fails to start

### ISSUE THREAD

**Issue by dhoer** [dhoer/chef-selenium#22]
When running Firefox on Ubuntu you get the following error:

```
 Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

   (process:14883): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
   Xlib:  extension "RANDR" missing on display ":0".
   ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
   ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
   ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
   ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
   ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
   ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
   ALSA lib conf.c:4727:(snd_config_expand) Evaluate error: No such file or directory
   ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM default
    (org.openqa.selenium.firefox.NotConnectedException)
        # [remote server] org.openqa.selenium.firefox.internal.NewProfileExtensionConnection(NewProfileExtensionConnection.java):122:in `start'
        # [remote server] org.openqa.selenium.firefox.FirefoxDriver(FirefoxDriver.java):276:in `startClient'
        # [remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):116:in `<init>'
        # [remote server] org.openqa.selenium.firefox.FirefoxDriver(FirefoxDriver.java):223:in `<init>'
        # [remote server] org.openqa.selenium.firefox.FirefoxDriver(FirefoxDriver.java):216:in `<init>'
        # [remote server] org.openqa.selenium.firefox.FirefoxDriver(FirefoxDriver.java):134:in `<init>'
        # [remote server] sun.reflect.NativeConstructorAccessorImpl(NativeConstructorAccessorImpl.java):-2:in `newInstance0'
      # [remote server] sun.reflect.NativeConstructorAccessorImpl(NativeConstructorAccessorImpl.java):62:in `newInstance'
        # [remote server] sun.reflect.DelegatingConstructorAccessorImpl(DelegatingConstructorAccessorImpl.java):45:in `newInstance'
        # [remote server] java.lang.reflect.Constructor(Constructor.java):422:in `newInstance'
        # [remote server] org.openqa.selenium.remote.server.DefaultDriverProvider(DefaultDriverProvider.java):103:in `callConstructor'
        # [remote server] org.openqa.selenium.remote.server.DefaultDriverProvider(DefaultDriverProvider.java):97:in `newInstance'
        # [remote server] org.openqa.selenium.remote.server.DefaultDriverFactory(DefaultDriverFactory.java):60:in `newInstance'
        # [remote server] org.openqa.selenium.remote.server.DefaultSession$BrowserCreator(DefaultSession.java):222:in `call'
        # [remote server] org.openqa.selenium.remote.server.DefaultSession$BrowserCreator(DefaultSession.java):1:in `call'
        # [remote server] java.util.concurrent.FutureTask(FutureTask.java):266:in `run'
        # [remote server] org.openqa.selenium.remote.server.DefaultSession$1(DefaultSession.java):176:in `run'
        # [remote server] java.util.concurrent.ThreadPoolExecutor(ThreadPoolExecutor.java):1142:in `runWorker'
        # [remote server] java.util.concurrent.ThreadPoolExecutor$Worker(ThreadPoolExecutor.java):617:in `run'
        # [remote server] java.lang.Thread(Thread.java):745:in `run'
        # /tmp/verifier/gems/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
        # /tmp/verifier/gems/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
        # /tmp/verifier/gems/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
        # /tmp/verifier/gems/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
        # /tmp/verifier/gems/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
        # /tmp/verifier/gems/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
        # /tmp/verifier/gems/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:657:in `raw_execute'
        # /tmp/verifier/gems/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:122:in `create_session'
        # /tmp/verifier/gems/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:87:in `initialize'
        # /tmp/verifier/gems/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/driver.rb:52:in `new'
        # /tmp/verifier/gems/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/driver.rb:52:in `for'
        # /tmp/verifier/gems/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver.rb:86:in `for'
        # ./firefox_spec.rb:5:in `block (2 levels) in <top (required)>'
        # /tmp/verifier/gems/gems/busser-rspec-0.7.5/lib/busser/rspec/runner.rb:23:in `<main>'
```

**Comment by dhoer** [comment]
To run firefox as a non-root user, you need to make sure that user has a home directory.
http://stackoverflow.com/questions/5782055/running-seleniumwebdriverfirefox-inside-xvfb-from-ruby-as-non-root-user
